// Generated by scripts/build_spiti_book.py — do not edit by hand.
// Caches the whole spiti/ site for offline use. Each build gets a new VERSION; installed
// copies then download the new files in the background and pages offer "Update" (pwa.js).
const VERSION = "fc92b872";
const CACHE = `spiti-${VERSION}`;
const RUNTIME = "spiti-runtime";
const PRECACHE = [
["book/img/010e-wild-bearded-vulture-in-flight-at-pfyn-finges-switzerla.webp", 26888, "b425a08c1895"],
["book/img/015-wild-golden-eagle-in-flight-at-pfyn-finges-switzerland-p.webp", 25268, "9e5f75176752"],
["book/img/1000-year-loop.webp", 107394, "ecc25f3f512b"],
["book/img/6934-juniperus-semiglobosa-dz-09-15.webp", 109502, "3b3abf8eac78"],
["book/img/a-folk-procession-in-shimla.webp", 77192, "908cd87ec8e1"],
["book/img/a-scenic-view-of-sangla-valley-kamru-fort-forests-in-himacha.webp", 99292, "10fbb1d5ec48"],
["book/img/a-view-of-sutlej-river-himachal-pradesh-india-2014.webp", 104584, "c56a70703f19"],
["book/img/andromeda-galaxy-2025.webp", 32302, "29b5381c4e2d"],
["book/img/apricot-and-cross-section.webp", 6468, "8df275c49c05"],
["book/img/arak-with-water-and-ice.webp", 8828, "9e9d2b2629e2"],
["book/img/arbi-colocasia-pakoda-fritters.webp", 25102, "3a7bab8a3d63"],
["book/img/atal-tunnel-vrtmrgmpksk-2.webp", 106550, "17501c4585b8"],
["book/img/balep-korkun-the-tibetan-bread-photographed-in-nepal-decembe.webp", 46274, "10cf86f59469"],
["book/img/batal-06-chandra-dhaba-gje.webp", 86562, "cc7304d10025"],
["book/img/batal-11-chandra-dhaba-2016-gje.webp", 44698, "296a5f2cfa04"],
["book/img/beas-river-at-manali.webp", 64670, "d4f58c9725c0"],
["book/img/bharal-shreeram-m-v-kibber-spiti-valley-himachal-pradesh-ind.webp", 115120, "8dd3fec22fa9"],
["book/img/bhimakali-temple.webp", 200212, "8ca0f9fe9121"],
["book/img/bijli-mahadev-temple.webp", 26244, "938ae190ee6a"],
["book/img/borax-crystals.webp", 9430, "aafc172184ec"],
["book/img/buddha-in-sarnath-museum-dhammajak-mutra.webp", 27706, "604482841406"],
["book/img/buddha-vairocana-google-art-project.webp", 85972, "23b48663796e"],
["book/img/captive-tragopan-melanocephalus-male-at-sarahan-pheasantry-h.webp", 191178, "7326b8b6df2b"],
["book/img/caragana-versicolor-shrubs-kibber-spiti-jun18-d72-7261.webp", 59264, "fdecfacbfd31"],
["book/img/cedrus-deodara-manali-2.webp", 137404, "0330d1730943"],
["book/img/chaimarrornis-leucocephalus-doi-inthanon.webp", 17942, "bc802af78502"],
["book/img/cham-dance-during-dosmoche-festival-in-leh-palace-dscn5689-1.webp", 287278, "ef6738f694ce"],
["book/img/chandra-tributary-rohtang-lahaul-jul19-d72-10383.webp", 150502, "840f206af495"],
["book/img/chandratal-1.webp", 34278, "d175127e5259"],
["book/img/chhurpi-nep.webp", 21982, "cdd54861c875"],
["book/img/chhyang-or-chhaang-fermented-rice-drink-8902831091.webp", 38006, "1ca194a2c3cf"],
["book/img/chicham-bridge-spiti-himachal-jun18-d72-7433.webp", 214730, "9a0f718dd745"],
["book/img/confluence-chandra-bhaga-lahaul-oct22-a7c-03346.webp", 207980, "ec8a426f6206"],
["book/img/confluence-spiti-satluj-jun18-d72-6744.webp", 196558, "e0762741674b"],
["book/img/crossing-the-sutlej-near-simla-upon-inflated-animal-skins.webp", 25638, "91181cd434b8"],
["book/img/damsite-of-karcham-wangtoo-project-at-karcham-kinnaur.webp", 144306, "81815ffa2450"],
["book/img/dhankar-gompa-25-klosterburg-2016-gje.webp", 138422, "1b93b820044b"],
["book/img/dhankar-gompa-and-village.webp", 102142, "a2864e7d24df"],
["book/img/double-cluster.webp", 63806, "0a14cfb58b31"],
["book/img/downtown-kaza-spiti.webp", 96844, "46da708cb967"],
["book/img/downtown-reckong-peo-2010.webp", 125072, "581ab7aab945"],
["book/img/ephedra-gerardiana-botanischer-garten-dresden-germany-dsc087.webp", 77372, "21e2fa310865"],
["book/img/female-siberian-ibex-capra-sibirica-kargil.webp", 52264, "eaebbf3d9d42"],
["book/img/ferdinand-stolicka.webp", 120736, "c27a6da0a5d6"],
["book/img/figures/01-drainage.svg", 39587, "e60789ce5a9b"],
["book/img/figures/02-pare-chu.svg", 18212, "8e41c0421f70"],
["book/img/figures/03-passes.svg", 17289, "518133d2768a"],
["book/img/figures/04-elevation.svg", 30620, "dc492651f7df"],
["book/img/figures/05-kailash.svg", 17105, "2ee566afbf17"],
["book/img/figures/06-tabo-plan.svg", 80708, "ec012239b8b3"],
["book/img/figures/07-kath-kuni.svg", 28941, "2536c0711cba"],
["book/img/figures/08-wheel-of-life.svg", 36632, "572d247ee292"],
["book/img/five-dhyani-budhhas-of-nako-monastery-india.webp", 232246, "769f8bc14e32"],
["book/img/four-guardian-kings-in-burmese-art.webp", 27074, "48cf84cebb4f"],
["book/img/getting-ready-for-losar.webp", 180810, "8b2b9431add7"],
["book/img/ghepan-monastery-prayer-stones-sissu-lahaul-oct20-d72-18647.webp", 296746, "613bd2dc446b"],
["book/img/gondla-fort-lahaul-d32-13430.webp", 284808, "988e2989c2ec"],
["book/img/gurdwara-at-manikarn.webp", 31856, "a50ce24185e6"],
["book/img/guru-rinpoche-in-mist-2.webp", 19322, "bb96c7da9e4f"],
["book/img/hatu-peak.webp", 157100, "52e6180d7abe"],
["book/img/hidimba-devi-temple-north-east-view-manali-2014-05-11-2648-2.webp", 255270, "133bb111ef7f"],
["book/img/hikkim-the-worlds-highest-post-office.webp", 135136, "76c188ebd6ed"],
["book/img/himalayan-griffon-gyps-himalayensis.webp", 29256, "34a0b7c90940"],
["book/img/himalayan-marmot-at-tshophu-lake-bhutan-091007-b.webp", 295254, "7ebee8ec3b8f"],
["book/img/himalayan-snowcock-from-ladakh.webp", 36676, "bbcf192ddee4"],
["book/img/himalayn-national-park-01.webp", 30522, "d5eec14ee582"],
["book/img/hindustan-tibet-highway.webp", 101840, "567e10f9a3be"],
["book/img/hippophae-rhamnoides-01-xndr.webp", 110868, "acbf86ab9cbe"],
["book/img/hungarung-pass-in-the-himalayas-nowadays-called-shipki-la-wh.webp", 118828, "5a8d1b2a9d9c"],
["book/img/ice-cave-at-the-bara-shigri-terminus-1863.webp", 270692, "2038bdf3fded"],
["book/img/iias-formerly-viceregal-lodge-shimla.webp", 110554, "70be8b642773"],
["book/img/illustrations-of-tibetan-materia-medica-wellcome-l0038345.webp", 216736, "19d69d2343f9"],
["book/img/inhabitant-of-chitkul.webp", 174846, "8d10287f096a"],
["book/img/inside-of-kalpa-temple-kinnaur.webp", 60584, "eac8e81e35c4"],
["book/img/irbis4.webp", 92928, "2636ad9ed7e6"],
["book/img/israel-eurasian-hoopoe-6497645007.webp", 46814, "245d33915e0a"],
["book/img/japanese-buckwheat-flower.webp", 13554, "8eab5f94f7fe"],
["book/img/kalpa-8512894537.webp", 167844, "8fab6b43c8cb"],
["book/img/kardhang-biling-bhaga-dhauladhar-oct22-a7c-04645.webp", 245446, "a61880a73b03"],
["book/img/kath-kuni-house-in-himachal.webp", 46270, "8378f964ef42"],
["book/img/kath-kuni-house-wall-with-beehive-niches-in-thundal-shimla-d.webp", 48338, "fb44de7ad991"],
["book/img/khasarpana-lokesvara.webp", 28748, "8c43c91c99b2"],
["book/img/khata.webp", 95826, "78542e6c7ae0"],
["book/img/kibber-20-traditionelles-haus-gje.webp", 138958, "ec07208962bf"],
["book/img/kibber-a-villege-in-spiti.webp", 147894, "722028a75440"],
["book/img/kinnaur-kailash-shivling-and-kinnaur-kailash-with-top-of-kal.webp", 150598, "56d149625203"],
["book/img/kinnauri-bridal-cap-or-kir-kir-the-pang.webp", 57826, "667f20f6aa18"],
["book/img/kinnauri-culture.webp", 53862, "b546ff9841b9"],
["book/img/kinnauri-nati-dance.webp", 66318, "d109c87b08ea"],
["book/img/komic-village.webp", 162916, "7de64855d560"],
["book/img/korosi-csoma-sandor.webp", 71604, "8dac2d15eb1d"],
["book/img/ksr-steam-special-at-taradevi-05-02-13-56.webp", 143096, "b8d2e4901fd9"],
["book/img/kullu-dussehra-main-procession.webp", 179216, "1cf597683845"],
["book/img/kullu-valley-vashisht-manali-apples-india.webp", 94956, "8246ce531b68"],
["book/img/kungri-monastery-india.webp", 160218, "e0c2fe1ad88a"],
["book/img/kunzom-pass-temple.webp", 38348, "28f9ed2d0966"],
["book/img/langza-village-and-buddha-statue.webp", 149452, "a626edd262ba"],
["book/img/langza-village-himachal-pradesh.webp", 123576, "07ae5222e87b"],
["book/img/leo-spiti-nh505-himachal-jun18-d72-6785.webp", 166710, "ab4aba12e278"],
["book/img/light-butter-lamps.webp", 39628, "16ee3418d909"],
["book/img/losar-jun18-d72-7824.webp", 182534, "f7e53c11d749"],
["book/img/losar-kunzum-road-jun18-d72-7836.webp", 244180, "85ff7052596c"],
["book/img/losar-spiti-scree-left-himachal-jun18-d72-7825.webp", 45806, "0d7ecd46e704"],
["book/img/mahakala-and-companions-lacma-m-77-19-11.webp", 82352, "23c9fb81d1c1"],
["book/img/mahavairocana.webp", 99904, "076a9d2d8503"],
["book/img/manali-city.webp", 234584, "f86c6d2db96d"],
["book/img/manjusri-kumara-bodhisattva-of-wisdom-india-pala-dynesty-9th.webp", 59978, "d3771809543c"],
["book/img/map-ch01-03-shimla-sarahan.svg", 44486, "50b40281822d"],
["book/img/map-ch04-baspa.svg", 22934, "f1132cbf1276"],
["book/img/map-ch05-kalpa.svg", 21509, "1fc8031d4b94"],
["book/img/map-ch06-the-long-drive.svg", 30350, "09156ebbde59"],
["book/img/map-ch08-10-tabo-dhankar-pin.svg", 22852, "8d3fdde44f15"],
["book/img/map-ch09-dhankar-closeup.svg", 13417, "131ab6bc6b26"],
["book/img/map-ch11-12-kaza-high-villages.svg", 28383, "b6c66a000407"],
["book/img/map-ch13-14-losar-kunzum-chandratal.svg", 14826, "1aa763e7d7f0"],
["book/img/map-ch15-chandra-valley-manali.svg", 24664, "1452d54c7f42"],
["book/img/map-summer-triangle.webp", 19754, "35624ef9b544"],
["book/img/milky-way-night-sky-black-rock-desert-nevada.webp", 245046, "b06b2117dbf3"],
["book/img/momo-nepal.webp", 20388, "c931487a873b"],
["book/img/monk-with-pot-of-butter-tea-at-key-monastry-spiti-india.webp", 55222, "6fbee06e130d"],
["book/img/morning-scene-in-thuskeo-dhar.webp", 110760, "08b9e670d703"],
["book/img/mountain-peaks-as-seen-from-kunzum-pass-between-lahaul-and-s.webp", 104190, "e0d46399fa44"],
["book/img/mudh-village-pin-spiti-himachal-jun18-d72-7094.webp", 56200, "b07d2137b17d"],
["book/img/murals-at-kungri-gompha-india.webp", 168714, "64801eef61c1"],
["book/img/naggar-castle-2.webp", 167786, "483d071ea515"],
["book/img/nainsingh.webp", 9124, "4f8374d3c7fe"],
["book/img/nako-lake-and-nako-village-himachal-pradesh.webp", 180470, "c94d89a058d4"],
["book/img/narkanda.webp", 74034, "48cc981052da"],
["book/img/nh505-spiti-kaza-losar-jun18-d72-7797.webp", 137894, "b58a706d96f5"],
["book/img/old-green-tara.webp", 101386, "4644d13f3930"],
["book/img/old-statues-lhalung.webp", 281690, "c655030804e6"],
["book/img/old-structure-in-the-temple-premises-at-kamru-fort-184257918.webp", 195230, "8ee4748b71a5"],
["book/img/pashmina-goats.webp", 203854, "32359901797c"],
["book/img/pea-plants-mudh-spiti-himachal-jun18-d72-7222.webp", 186588, "7bd8f8219e6e"],
["book/img/pinus-gerardiana-female-cone.webp", 67898, "45c0eda6a828"],
["book/img/pleiades-large.webp", 15544, "e1a97f1bcbc3"],
["book/img/pleuroceras-solare-little-switzerland-bavaria-germany.webp", 202714, "0647f6c5b639"],
["book/img/portrait-of-a-red-fox-in-rautas-fjallurskog-cropped.webp", 19962, "cebe24e17f96"],
["book/img/prayerflags.webp", 32454, "9e04f24b381e"],
["book/img/prayers-on-stones-outside-the-tsuglagkhang-complex-mcleod-ga.webp", 170488, "cd025097951a"],
["book/img/preparing-butter-lamps-at-thag-thok-gompa-2010.webp", 105716, "09a61e900e4f"],
["book/img/rahul-sankrityayan-bust-darjeeling.webp", 170246, "6c92b5c014ab"],
["book/img/rajma-masala-32081557778.webp", 30754, "a39731d875ed"],
["book/img/rheum-rhabarbarum-2006-04-27-uellue.webp", 93196, "884e9d91d165"],
["book/img/right-bank-pin-mudh-spiti-himachal-jun18-d72-7114.webp", 38982, "996d4aea108a"],
["book/img/route-map-base.webp", 207494, "74e05bcb7981"],
["book/img/route-map-overlay.svg", 40848, "9ed2eec66f8b"],
["book/img/row-of-chortens-at-roadside-near-kaza-lahul-spiti.webp", 170348, "ea3f578bd083"],
["book/img/ruddy-shelduck-chandratal-spiti-himachal-jun18-d72-7911.webp", 35218, "a53f9a3678e8"],
["book/img/sangha-tenzin-monk-mummy.webp", 110696, "096d809abce9"],
["book/img/sarahan-bhimakali-temple.webp", 64782, "60b69aac0410"],
["book/img/sarahan-palace-hp.webp", 181958, "0bd3007a91a3"],
["book/img/sarlyk-yak2.webp", 34286, "3662fabaace0"],
["book/img/satyanand-stokes-with-local-children.webp", 70032, "95f86f191c0b"],
["book/img/shimla-1850s.webp", 106906, "9d2e6f2b3f66"],
["book/img/shipki-la.webp", 210192, "2673a14304da"],
["book/img/siddu-traditional-steamed-bread-from-himachal-pradesh.webp", 37700, "d63f8754b840"],
["book/img/spiti-river-kaza-himachal-jun18-d72-7232.webp", 187316, "484d0bf603b2"],
["book/img/spiti_circuit_route_map_sept_2026.svg", 38365, "876da1c988b9"],
["book/img/standing-bodhisattva-maitreya-buddha-of-the-future.webp", 12242, "26b6619c0735"],
["book/img/sudana-and-the-perfumer-tabo-monastery.webp", 186190, "80ed2dad3183"],
["book/img/sutlej-valley-from-rampur-ca-1857.webp", 30198, "eacee4628644"],
["book/img/tabomonastery-tabo-spiti-himachal-d72-6768.webp", 362312, "5cb538cf2616"],
["book/img/temple-at-chitkul.webp", 160158, "ebad71502f61"],
["book/img/thanka-in-making.webp", 15548, "8108630a539d"],
["book/img/the-great-kashmiri-salt-tea.webp", 66664, "af2d895f7c0d"],
["book/img/the-ridge-shimla-5.webp", 162784, "abbddb66446c"],
["book/img/thenthuk.webp", 17264, "3d21f729b004"],
["book/img/tholing-kloster-tibet-roter-tempel-dieter-schuh.webp", 240836, "87465394080e"],
["book/img/thukpa-tibetan-noodle-in-osaka-japan.webp", 23792, "12907ad1c12e"],
["book/img/tibetan-monastery-prayer-wheel.webp", 17878, "67607fef7717"],
["book/img/tibetan-snack-syabhaley-in-nepal.webp", 22608, "99bb104c5d07"],
["book/img/tingmo-traditional-tibetan-dish-prepared-during-fagli-festiv.webp", 23074, "b0e264a1c101"],
["book/img/torma-or-butter-sculptures-dhankar-gompa-spiti.webp", 40564, "88a2285cc38f"],
["book/img/traditional-kinnauri-house-sangla-himachal-pradesh-india.webp", 230586, "45a5eba63276"],
["book/img/traditional-slate-roof-house-in-sohja-valley-himachal-prades.webp", 49512, "eec698640f6d"],
["book/img/traffic-jam-on-road-to-rohtang-pass.webp", 236284, "75bfab4c547b"],
["book/img/tsampainabowl.webp", 34508, "67c27fa9c974"],
["book/img/tsonkapa-16th-century-collection-of-rubin-museum-of-art.webp", 113810, "f9c8a64250c1"],
["book/img/vajrapani-from-rig-sum-gonpo-lords-of-the-three-families-vie.webp", 54356, "741208bd7ebd"],
["book/img/ved-prakash-solang-valley-2014-05-10-2547.webp", 253254, "df717a67fae7"],
["book/img/wallcreeper-tichodroma-muraria-51181111456.webp", 16108, "d2781eec349e"],
["book/img/wheel-of-existence.webp", 139140, "a8af21a68e57"],
["book/img/white-chana-madra.webp", 32450, "975ffa5c7abc"],
["book/img/william-moorcroft-and-hyder-young-hearsey.webp", 67092, "38a138447c2e"],
["book/img/women-hoeing-barley-chicham-spiti-jun18-d72-7456.webp", 329152, "5e1129e5b07c"],
["book/img/woodblock-printing-sera-tibet.webp", 27108, "5bd0c9f8e87a"],
["book/img/yellow-billed-chough-kibber-jun18-dsc00094.webp", 16806, "2447aadbdf0b"],
["book/img/zhuan-cha.webp", 56518, "dfe0a2ba9d12"],
["book/", 848898, "a94807bed451"],
["book/search-index.json", 318203, "0b383293c2d3"],
["book/vendor/minisearch-7.2.0.min.js", 18556, "8a05b42785db"],
["icons/apple-touch-icon.png", 3855, "26c50515c418"],
["icons/icon-192.png", 4688, "8b00ec8f2c61"],
["icons/icon-512.png", 12109, "9357b4be864d"],
["icons/maskable-512.png", 10950, "b169a4516609"],
["./", 8648, "07c1f2126cf9"],
["manifest.webmanifest", 785, "8f76a73ced39"],
["map/", 21451, "396983f4f5cc"],
["map/route-data.json", 5638, "008ebc4ac5b3"],
["map/route.geojson", 11544, "bc37206ca18c"],
["practical/", 46564, "3ba00e2f1d12"],
["preparation/_ds/classical-f8f64dfe-8466-474e-844c-beca58a723d3/_ds_bundle.js", 303, "48a764927636"],
["preparation/_ds/classical-f8f64dfe-8466-474e-844c-beca58a723d3/styles.css", 11011, "506061661832"],
["preparation/", 75079, "9883454e4c91"],
["preparation/support.js", 69151, "eae8be66d3db"],
["pwa.js", 9488, "bcb7d4a46849"]
];
const EXTERNAL = [
 "https://unpkg.com/react@18.3.1/umd/react.production.min.js",
 "https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js",
 "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600&family=Lora:wght@400;600&display=swap",
 "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600&family=Lora:wght@400;600&display=swap",
 "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400&family=Lora:ital,wght@0,400;0,600;1,400&display=swap",
 "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css",
 "https://unpkg.com/leaflet@1.9.4/dist/leaflet.js",
 "https://fonts.googleapis.com/css2?family=Barlow:wght@400;500;600&family=Barlow+Semi+Condensed:wght@500;600&display=swap"
];
const RUNTIME_HOSTS = ["fonts.googleapis.com", "fonts.gstatic.com", "unpkg.com"];   // third-party hosts worth keeping offline; map tiles are not
const keepable = url => RUNTIME_HOSTS.includes(new URL(url).hostname);

const fill = (cache, url) =>
  cache.match(url, { ignoreVary: true })
    .then(hit => hit || fetch(url, { mode: "cors" }).then(res => res.ok && cache.put(url, res)))
    .catch(() => {});

const TOTAL_BYTES = PRECACHE.reduce((n, [, size]) => n + size, 0);
const tell = async msg => {
  for (const c of await self.clients.matchAll({ includeUncontrolled: true, type: "window" })) c.postMessage(msg);
};

// PRECACHE is [url, bytes, content hash]. Files whose hash matches the previous version are copied from
// the old cache instead of downloaded again, so an update only fetches what actually changed.
self.addEventListener("install", event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const old = [];
    for (const key of await caches.keys())
      if (key.startsWith("spiti-") && key !== CACHE && key !== RUNTIME) old.push(await caches.open(key));
    const queue = PRECACHE.slice();
    let done = 0, bytes = 0, last = 0, reused = 0;
    const progress = async force => {
      if (!force && Date.now() - last < 250) return;
      last = Date.now();
      await tell({ type: "progress", version: VERSION, done, total: PRECACHE.length, bytes, totalBytes: TOTAL_BYTES });
    };
    const one = async ([url, size, hash]) => {
      for (const c of old) {
        const hit = await c.match(url);
        if (hit && hit.headers.get("x-spiti-hash") === hash) {
          await cache.put(url, hit);
          reused++;
          return;
        }
      }
      const res = await fetch(new Request(url, { cache: "reload" }));
      if (!res.ok) throw new Error(`${url} (${res.status})`);
      const headers = new Headers(res.headers);
      headers.set("x-spiti-hash", hash);
      await cache.put(url, new Response(await res.blob(), { status: res.status, statusText: res.statusText, headers }));
    };
    const worker = async () => {
      while (queue.length) {
        const item = queue.shift();
        await one(item);
        done++;
        bytes += item[1];
        progress(false);
      }
    };
    try {
      await Promise.all(Array.from({ length: 6 }, worker));
    } catch (err) {
      await tell({ type: "install-failed", version: VERSION, error: String(err.message || err) });
      throw err;
    }
    await progress(true);
    const runtime = await caches.open(RUNTIME);
    await Promise.all(EXTERNAL.map(url => fill(runtime, url)));
    await tell({ type: "installed", version: VERSION, files: PRECACHE.length, bytes: TOTAL_BYTES, reused });
  })());
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys())
      if (key.startsWith("spiti-") && key !== CACHE && key !== RUNTIME) await caches.delete(key);
    await self.clients.claim();
  })());
});

self.addEventListener("message", event => {
  const data = event.data || {};
  if (data.type === "skip-waiting") self.skipWaiting();
  if (data.type === "version" && event.source) event.source.postMessage({ type: "version", version: VERSION });
  if (data.type === "status" && event.source)
    event.waitUntil(caches.open(CACHE).then(c => c.keys()).then(keys => event.source.postMessage({
      type: "status", version: VERSION, files: PRECACHE.length, have: keys.length, bytes: TOTAL_BYTES,
      complete: keys.length >= PRECACHE.length })));
  if (data.type === "cache" && Array.isArray(data.urls))
    event.waitUntil(caches.open(RUNTIME).then(runtime => Promise.all(
      data.urls.filter(keepable).map(url => fill(runtime, url)))));
});

self.addEventListener("fetch", event => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);

  if (url.origin === location.origin) {
    if (!url.pathname.startsWith(new URL(self.registration.scope).pathname)) return;
    // the site itself: cache first; new content arrives through a service-worker update
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const hit = await cache.match(request, { ignoreSearch: true });
      if (hit) return hit;
      try {
        return await fetch(request);
      } catch (err) {
        if (request.mode === "navigate")
          return (await cache.match(url.pathname.replace(/[^/]*$/, ""))) || (await cache.match("./"));
        throw err;
      }
    })());
    return;
  }

  // fonts and scripts from other sites: cache first, filled on first use.
  // Anything else (map tiles) goes straight to the network so it cannot fill the phone's storage.
  if (!keepable(request.url)) return;
  event.respondWith((async () => {
    const runtime = await caches.open(RUNTIME);
    const hit = await runtime.match(request, { ignoreVary: true });
    if (hit) return hit;
    const res = await fetch(request);
    if (res.ok || res.type === "opaque") runtime.put(request, res.clone());
    return res;
  })());
});
