// Generated by scripts/build_spiti_book.py — do not edit by hand.
// Caches the whole spiti/ site for offline use. Each build gets a new VERSION; installed
// copies then download the new files in the background and pages offer "Update" (pwa.js).
const VERSION = "a775e01c";
const CACHE = `spiti-${VERSION}`;
const RUNTIME = "spiti-runtime";
const PRECACHE = [
 "book/img/1000-year-loop.webp",
 "book/img/a-folk-procession-in-shimla.webp",
 "book/img/a-scenic-view-of-sangla-valley-kamru-fort-forests-in-himacha.webp",
 "book/img/a-view-of-sutlej-river-himachal-pradesh-india-2014.webp",
 "book/img/atal-tunnel-vrtmrgmpksk-2.webp",
 "book/img/beas-river-at-manali.webp",
 "book/img/bharal-shreeram-m-v-kibber-spiti-valley-himachal-pradesh-ind.webp",
 "book/img/bhimakali-temple.webp",
 "book/img/captive-tragopan-melanocephalus-male-at-sarahan-pheasantry-h.webp",
 "book/img/cham-dance-during-dosmoche-festival-in-leh-palace-dscn5689-1.webp",
 "book/img/chandra-tributary-rohtang-lahaul-jul19-d72-10383.webp",
 "book/img/chandratal-1.webp",
 "book/img/chicham-bridge-spiti-himachal-jun18-d72-7433.webp",
 "book/img/confluence-chandra-bhaga-lahaul-oct22-a7c-03346.webp",
 "book/img/confluence-spiti-satluj-jun18-d72-6744.webp",
 "book/img/crossing-the-sutlej-near-simla-upon-inflated-animal-skins.webp",
 "book/img/damsite-of-karcham-wangtoo-project-at-karcham-kinnaur.webp",
 "book/img/dhankar-gompa-25-klosterburg-2016-gje.webp",
 "book/img/dhankar-gompa-and-village.webp",
 "book/img/downtown-kaza-spiti.webp",
 "book/img/downtown-reckong-peo-2010.webp",
 "book/img/ferdinand-stolicka.webp",
 "book/img/five-dhyani-budhhas-of-nako-monastery-india.webp",
 "book/img/getting-ready-for-losar.webp",
 "book/img/ghepan-monastery-prayer-stones-sissu-lahaul-oct20-d72-18647.webp",
 "book/img/gondla-fort-lahaul-d32-13430.webp",
 "book/img/hatu-peak.webp",
 "book/img/hidimba-devi-temple-north-east-view-manali-2014-05-11-2648-2.webp",
 "book/img/hikkim-the-worlds-highest-post-office.webp",
 "book/img/himalayan-marmot-at-tshophu-lake-bhutan-091007-b.webp",
 "book/img/hindustan-tibet-highway.webp",
 "book/img/hungarung-pass-in-the-himalayas-nowadays-called-shipki-la-wh.webp",
 "book/img/ice-cave-at-the-bara-shigri-terminus-1863.webp",
 "book/img/iias-formerly-viceregal-lodge-shimla.webp",
 "book/img/illustrations-of-tibetan-materia-medica-wellcome-l0038345.webp",
 "book/img/inhabitant-of-chitkul.webp",
 "book/img/irbis4.webp",
 "book/img/kalpa-8512894537.webp",
 "book/img/kardhang-biling-bhaga-dhauladhar-oct22-a7c-04645.webp",
 "book/img/khata.webp",
 "book/img/kibber-20-traditionelles-haus-gje.webp",
 "book/img/kibber-a-villege-in-spiti.webp",
 "book/img/kinnaur-kailash-shivling-and-kinnaur-kailash-with-top-of-kal.webp",
 "book/img/kinnauri-nati-dance.webp",
 "book/img/komic-village.webp",
 "book/img/korosi-csoma-sandor.webp",
 "book/img/ksr-steam-special-at-taradevi-05-02-13-56.webp",
 "book/img/kullu-dussehra-main-procession.webp",
 "book/img/kullu-valley-vashisht-manali-apples-india.webp",
 "book/img/kungri-monastery-india.webp",
 "book/img/kunzom-pass-temple.webp",
 "book/img/langza-village-and-buddha-statue.webp",
 "book/img/langza-village-himachal-pradesh.webp",
 "book/img/leo-spiti-nh505-himachal-jun18-d72-6785.webp",
 "book/img/losar-jun18-d72-7824.webp",
 "book/img/losar-kunzum-road-jun18-d72-7836.webp",
 "book/img/manali-city.webp",
 "book/img/milky-way-night-sky-black-rock-desert-nevada.webp",
 "book/img/monk-with-pot-of-butter-tea-at-key-monastry-spiti-india.webp",
 "book/img/morning-scene-in-thuskeo-dhar.webp",
 "book/img/mountain-peaks-as-seen-from-kunzum-pass-between-lahaul-and-s.webp",
 "book/img/murals-at-kungri-gompha-india.webp",
 "book/img/naggar-castle-2.webp",
 "book/img/nainsingh.webp",
 "book/img/nako-lake-and-nako-village-himachal-pradesh.webp",
 "book/img/narkanda.webp",
 "book/img/nh505-spiti-kaza-losar-jun18-d72-7797.webp",
 "book/img/old-statues-lhalung.webp",
 "book/img/old-structure-in-the-temple-premises-at-kamru-fort-184257918.webp",
 "book/img/pashmina-goats.webp",
 "book/img/pea-plants-mudh-spiti-himachal-jun18-d72-7222.webp",
 "book/img/pinus-gerardiana-female-cone.webp",
 "book/img/pleuroceras-solare-little-switzerland-bavaria-germany.webp",
 "book/img/prayers-on-stones-outside-the-tsuglagkhang-complex-mcleod-ga.webp",
 "book/img/preparing-butter-lamps-at-thag-thok-gompa-2010.webp",
 "book/img/rahul-sankrityayan-bust-darjeeling.webp",
 "book/img/row-of-chortens-at-roadside-near-kaza-lahul-spiti.webp",
 "book/img/sangha-tenzin-monk-mummy.webp",
 "book/img/sarahan-bhimakali-temple.webp",
 "book/img/sarahan-palace-hp.webp",
 "book/img/satyanand-stokes-with-local-children.webp",
 "book/img/shimla-1850s.webp",
 "book/img/shipki-la.webp",
 "book/img/spiti-river-kaza-himachal-jun18-d72-7232.webp",
 "book/img/sudana-and-the-perfumer-tabo-monastery.webp",
 "book/img/sutlej-valley-from-rampur-ca-1857.webp",
 "book/img/tabomonastery-tabo-spiti-himachal-d72-6768.webp",
 "book/img/temple-at-chitkul.webp",
 "book/img/the-ridge-shimla-5.webp",
 "book/img/tholing-kloster-tibet-roter-tempel-dieter-schuh.webp",
 "book/img/traditional-kinnauri-house-sangla-himachal-pradesh-india.webp",
 "book/img/traffic-jam-on-road-to-rohtang-pass.webp",
 "book/img/ved-prakash-solang-valley-2014-05-10-2547.webp",
 "book/img/wheel-of-existence.webp",
 "book/img/william-moorcroft-and-hyder-young-hearsey.webp",
 "book/img/women-hoeing-barley-chicham-spiti-jun18-d72-7456.webp",
 "book/",
 "icons/apple-touch-icon.png",
 "icons/icon-192.png",
 "icons/icon-512.png",
 "icons/maskable-512.png",
 "./",
 "manifest.webmanifest",
 "preparation/_ds/classical-f8f64dfe-8466-474e-844c-beca58a723d3/_ds_bundle.js",
 "preparation/_ds/classical-f8f64dfe-8466-474e-844c-beca58a723d3/styles.css",
 "preparation/",
 "preparation/support.js",
 "pwa.js"
];
const EXTERNAL = [
 "https://unpkg.com/react@18.3.1/umd/react.production.min.js",
 "https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js",
 "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600&family=Lora:wght@400;600&display=swap",
 "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600&family=Lora:wght@400;600&display=swap",
 "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400&family=Lora:ital,wght@0,400;0,600;1,400&display=swap"
];

const fill = (cache, url) =>
  cache.match(url, { ignoreVary: true })
    .then(hit => hit || fetch(url, { mode: "cors" }).then(res => res.ok && cache.put(url, res)))
    .catch(() => {});

self.addEventListener("install", event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await cache.addAll(PRECACHE.map(url => new Request(url, { cache: "reload" })));
    const runtime = await caches.open(RUNTIME);
    await Promise.all(EXTERNAL.map(url => fill(runtime, url)));
  })());
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys())
      if (key.startsWith("spiti-") && key !== CACHE && key !== RUNTIME) await caches.delete(key);
    await self.clients.claim();
  })());
});

self.addEventListener("message", event => {
  const data = event.data || {};
  if (data.type === "skip-waiting") self.skipWaiting();
  if (data.type === "version" && event.source) event.source.postMessage({ type: "version", version: VERSION });
  if (data.type === "cache" && Array.isArray(data.urls))
    event.waitUntil(caches.open(RUNTIME).then(runtime => Promise.all(
      data.urls.filter(url => new URL(url).origin !== location.origin).map(url => fill(runtime, url)))));
});

self.addEventListener("fetch", event => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);

  if (url.origin === location.origin) {
    if (!url.pathname.startsWith(new URL(self.registration.scope).pathname)) return;
    // the site itself: cache first; new content arrives through a service-worker update
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const hit = await cache.match(request, { ignoreSearch: true });
      if (hit) return hit;
      try {
        return await fetch(request);
      } catch (err) {
        if (request.mode === "navigate")
          return (await cache.match(url.pathname.replace(/[^/]*$/, ""))) || (await cache.match("./"));
        throw err;
      }
    })());
    return;
  }

  // fonts and scripts from other sites: cache first, filled on first use
  event.respondWith((async () => {
    const runtime = await caches.open(RUNTIME);
    const hit = await runtime.match(request, { ignoreVary: true });
    if (hit) return hit;
    const res = await fetch(request);
    if (res.ok || res.type === "opaque") runtime.put(request, res.clone());
    return res;
  })());
});
